015/master
ga-wdi-boston/express-api-deployment-guide pull request #2
Opened 2016-12-12 18:06 UTC by BenGitsCode

@gaand I’m able to to deploy successfully following these instructions, but your comment seems to allude to there being more changes to include here. 

Could you provide some feedback on what I have thus far?

2016-12-13 19:51 UTC, gaand reviewed
Please have a look at these notes and let me know if you have any questions.

2016-12-13 19:51 UTC, gaand commented on README.md
> +-   [ ] Tell Heroku to run your migration files (`heroku run rake db:migrate`).
This is rails specific

2016-12-13 19:51 UTC, gaand commented on README.md
> +    If you have any other rake tasks that need to run (e.g. `rake db:seed`), run
This too.

2016-12-13 19:51 UTC, gaand commented on README.md
> +-  [ ] in terminal, run : `heroku create`
This looks like a repeat

2016-12-13 19:51 UTC, gaand commented on README.md
> +-  [ ] in terminal run : `git remote -v` - make sure that heroku remote repo is pointing towards the newly created heroic url.   IF NOT, run this in terminal : `git remote set-url heroku <copy and pa
If heroku create fails, should they be doing this?

Also, spelling error.

2016-12-13 19:51 UTC, gaand commented on README.md
> +      `https://<% github username %>.github.io`
This should all say origin or ORIGIN, not url or URL

2016-12-13 21:44 UTC, gaand requested changes
Maybe I was supposed to select "Request changes"?

2016-12-13 21:44 UTC, gaand commented on README.md
> +-  [ ] commit to your local master branch
These seem inverted: push followed by commit

2016-12-13 21:44 UTC, gaand commented on README.md
> +-  [ ] in terminal run : `git remote -v` - make sure that heroku remote repo is pointing towards the newly created heroic url.   IF NOT, run this in terminal : `git remote set-url heroku <copy and pa
I'm still not comfortable with this since if the heroku url isn't set there may be a more serious problem.

Also, spelling: `heroic`

2016-12-13 21:44 UTC, gaand commented on README.md
> +-  [ ] You should have three config variables set in heroku (`heroku>settings>config vars`): MONGODB_URI, SECRET_KEY, CLIENT_URL
These still have to say ORIGIN.  Am I missing something?

2016-12-13 23:58 UTC, BenGitsCode commented
Nope, your notes were clear, I just hadn't read them 🐀 🔨

Thew new commits address your notes, as they should have the first time.

2016-12-13 23:58 UTC, BenGitsCode commented
Nope, your notes were clear, I just hadn't read them 🐀 🔨

Thew new commits address your notes, as they should have the first time.

2016-12-14 18:42 UTC, gaand reviewed
These are just questions.  I think this can probably be merged.

2016-12-14 18:42 UTC, gaand commented on README.md
> +1.  **sign up for mlab at mlab.com** / click link in verification email
Is this necessary or does having a credit card registered with heroku suffice?

2016-12-14 18:42 UTC, gaand commented on README.md
> +1.  **Make sure you have heroku tool belt installed for MAC**
Is this the same as the heroku command line tools?

2016-12-14 18:42 UTC, gaand commented on README.md
> +```
I think this should be indented 8 spaces.

2016-12-14 18:42 UTC, gaand commented on README.md
> +
Should we add a check for examples?

2016-12-14 20:15 UTC, merged